In [26]:
import pandas as pd

pd.set_option('display.max_columns', 500)

df_save = pd.read_csv("data.txt",sep=';')
df = pd.read_csv("data.txt",sep=';')

C:\Users\nagrimault\AppData\Local\Temp\ipykernel_18584\3283050720.py:5: DtypeWarning: Columns (1,2,5,6,7,8,9,15,16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_save = pd.read_csv("data.txt",sep=';')
C:\Users\nagrimault\AppData\Local\Temp\ipykernel_18584\3283050720.py:6: DtypeWarning: Columns (1,2,5,6,7,8,9,15,16,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data.txt",sep=';')

In [27]:
# df = df.drop(columns=["CodeDecision"]) # utile pour l'apprentissage mais pas prédiction 

df.head()

,ZIBZIN,IDAvisAutorisationCheque,FlagImpaye,Montant,DateTransaction,CodeDecision,VerifianceCPT1,VerifianceCPT2,VerifianceCPT3,D2CB,ScoringFP1,ScoringFP2,ScoringFP3,TauxImpNb_RB,TauxImpNB_CPM,EcartNumCheq,NbrMagasin3J,DiffDateTr1,DiffDateTr2,DiffDateTr3,CA3TRetMtt,CA3TR,Heure
0,A013010004908126703060931,78643044,0,20,2017-02-01 07:32:14,1,0,0,0,551,0,0,0,"37,186667890919111","52,076033757361408",0,1,4,4,4,20,0,27134
1,A013011306908024927155000,78643045,0,20,2017-02-01 07:43:37,1,0,0,0,551,0,0,0,"48,844716275908937","52,076033757361408",1,2,"1,7976851851851852",4,4,"28,609999999999999","8,6099999999999994",27817
2,A013010002908283134592527,78643046,0,"57,640000000000001",2017-02-01 07:47:38,1,0,0,0,549,0,0,0,"73,118279569892479","52,076033757361408",0,1,4,4,4,"57,640000000000001",0,28058
3,A011010002908105209831316,78643047,0,"54,289999999999999",2017-02-01 07:48:48,0,1,1,1,267,0,0,0,"110,05692599620494","53,554233554497365",0,1,4,4,4,"54,289999999999999",0,28128
4,A013010041908000125652029,78643048,0,"26,899999999999999",2017-02-01 08:13:27,1,0,0,0,549,"3,769090654336556E-3","8,5863334286662614","1,1922637097134124E-3","45,36831264567185","52,076033757361408",1,1,"1,9971064814814814",4,4,"59,149999999999999","32,25",29607

In [28]:
df["Montant"] = df["Montant"].str.replace(",", "").astype(float, errors='ignore')
df["VerifianceCPT1"] = df["VerifianceCPT1"].str.replace(",", "").astype(float, errors='ignore')
df["VerifianceCPT2"] = df["VerifianceCPT2"].str.replace(",", "").astype(float, errors='ignore')
df["VerifianceCPT3"] = df["VerifianceCPT3"].str.replace(",", "").astype(float, errors='ignore')
df["D2CB"] = df["D2CB"].str.replace(",", "").astype(float, errors='ignore')
df["ScoringFP1"] = df["ScoringFP1"].str.replace(",", "").astype(float, errors='ignore')
df["ScoringFP2"] = df["ScoringFP2"].str.replace(",", "").astype(float, errors='ignore')
df["ScoringFP3"] = df["ScoringFP3"].str.replace(",", "").astype(float, errors='ignore')
df["TauxImpNb_RB"] = df["TauxImpNb_RB"].str.replace(",", "").astype(float, errors='ignore')
df["TauxImpNB_CPM"] = df["TauxImpNB_CPM"].str.replace(",", "").astype(float, errors='ignore')
df["EcartNumCheq"] = df["EcartNumCheq"].str.replace(",", "").astype(float, errors='ignore')
df["NbrMagasin3J"] = df["NbrMagasin3J"].str.replace(",", "").astype(float, errors='ignore')
df["DiffDateTr1"] = df["DiffDateTr1"].str.replace(",", "").astype(float, errors='ignore')
df["DiffDateTr2"] = df["DiffDateTr2"].str.replace(",", "").astype(float, errors='ignore')
df["DiffDateTr3"] = df["DiffDateTr3"].str.replace(",", "").astype(float, errors='ignore')
df["CA3TRetMtt"] = df["CA3TRetMtt"].str.replace(",", "").astype(float, errors='ignore')
df["CA3TR"] = df["CA3TR"].str.replace(",", "").astype(float, errors='ignore')
df["Heure"] = df["Heure"].str.replace(",", "").astype(float, errors='ignore')

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4646774 entries, 0 to 4646773
Data columns (total 23 columns):
 #   Column                    Dtype
---  ------                    -----
 0   ZIBZIN                    object
 1   IDAvisAutorisationCheque  object
 2   FlagImpaye                object
 3   Montant                   object
 4   DateTransaction           object
 5   CodeDecision              object
 6   VerifianceCPT1            object
 7   VerifianceCPT2            object
 8   VerifianceCPT3            object
 9   D2CB                      object
 10  ScoringFP1                object
 11  ScoringFP2                object
 12  ScoringFP3                object
 13  TauxImpNb_RB              object
 14  TauxImpNB_CPM             object
 15  EcartNumCheq              object
 16  NbrMagasin3J              object
 17  DiffDateTr1               object
 18  DiffDateTr2               object
 19  DiffDateTr3               object
 20  CA3TRetMtt                object
 21  CA3TR                     object
 22  Heure                     object
dtypes: object(23)
memory usage: 815.4+ MB

In [30]:
df[['Date', 'Heure2']] = df['DateTransaction'].str.split(expand=True)
print(df['Date'])

#df = df.drop(columns=["DateTransaction"])

# Filtrer les transactions entre le 2017-02-01 et le 2017-08-31
date_debut = pd.to_datetime("2017-02-01")
date_fin = pd.to_datetime("2017-08-31")

df_apprentissage = df[(df['date'] >= date_debut) & (df['date'] <= date_fin)]

0          2017-02-01
1          2017-02-01
2          2017-02-01
3          2017-02-01
4          2017-02-01
              ...
4646769    2017-11-30
4646770    2017-11-30
4646771    2017-11-30
4646772    2017-11-30
4646773    2017-11-30
Name: Date, Length: 4646774, dtype: object

KeyError: 'date'

In [ ]:
df.describe()

In [ ]:
# https://www.kaggle.com/code/janiobachmann/credit-fraud-dealing-with-imbalanced-datasets